name: 'Image Diff Action'
description: 'GitHub Action for producing image diffs'
author: 'André Storhaug'
branding:
  icon: 'image'  
  color: 'purple'
inputs:
  img_1:
    description: 'The path to the image file used as base image.'
    required: true
  img_2:
    description: 'The path to the image file to be compared against the base image.'
    required: true
  mask:
    description: 'The path to the image file to be compared against the base image.'
    required: false
  error_color:
    description: 'Color for the error highlighting.'
    default: '255, 0, 255'
    required: false
  ignored_box:
    description: 'Area to be excluded from the top left in pixels (top, right, bottom, left).'
    default: '0, 0, 0, 0'
    required: false
outputs:
  img-diff:
    description: 'The image diff.'
  mismatch:
    description: 'The mismatch percentage'
runs:
  using: 'node12'
  main: 'src/index.js'
